version: 2

# Since we are uploading pre-built HTML files, we need a minimal build process
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# We don't need to install any Python dependencies
python:
  install: []

# Use Sphinx but point to our already built HTML
sphinx:
  configuration: conf.py
  fail_on_warning: false

formats: all