version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Use static HTML build
sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: false

# Do not install any Python dependencies
python:
  install: []

# Tell Read the Docs the output directory is the root directory
formats: []